### ISSUE TITLE
This is really cool. I have a question about how often `loadClass` is called.

### ISSUE THREAD

**Issue by collinalexbell** [brunoais/sandboxed-class-load#1]
Hi. Is `loadClass` called internaly by the JVM any time one class invokes a method to another class? Or is it called only once per class and the `resolveClass` maintains links that only classes loaded by that class loader have access to?

**Comment by collinalexbell** [comment]
NVM, I just read the JVM docs. `loadClass` is only called if a symbolic link to a class has not been resolved into a memory address. If the symbolic link hasn't been resolved, the calling class will ask its `defining loader (per JVM spec)` to load the class and optionally resolve it. I think each class has to individually get their symbolic links resolved, therefore each class can have different memory addresses for the same class name.

**Comment by brunoais** [comment]
@SlightlyCyborg Yep! Exactly!

**Comment by collinalexbell** [comment]
I built my own version https://github.com/SlightlyCyborg/holonJava/blob/master/src/holon/shell/ShellClassLoader.java

**Comment by brunoais** [comment]
@SlightlyCyborg Thanks for letting me know! I'll look into it later today.
